name = "cit-course-website"
account_id = "5ca4946aaee8c3a8d7a0bb168bdd2404"
compatibility_date = "2025-04-01"

[[pages.build]]
command = "npm run build"
dir = "dist"

pages_build_output_dir = "dist"

